/* ExOS d3dx.dll / three32.dll emulation
 * Version: 6.4.0-dev-os77
 * Model: EXOS_D3DX_V1
 * Three.js-backed high-level 3D scene API for XSH applications.
 * Host objects are process-local handles; raw host DOM/THREE objects never cross RPC.
 */
(function(global){
'use strict';
var API={version:'6.4.0-dev-os77',model:'EXOS_D3DX_V1',ready:true};
function exerr(status,msg){if(typeof global.jplopsoft_xshError==='function')return global.jplopsoft_xshError(status,msg);var e=new Error(msg);e.status=status;return e;}
function invalid(msg){return exerr(global.jplopsoft_STATUS_INVALID_HANDLE||0xC0000008,msg||'Invalid D3DX handle.');}
function unsupported(msg){return exerr(global.jplopsoft_STATUS_NOT_SUPPORTED||0xC00000BB,msg||'D3DX operation not supported.');}
function quota(msg){return exerr(global.jplopsoft_STATUS_QUOTA_EXCEEDED||0xC0000044,msg||'D3DX quota exceeded.');}
function param(msg){return exerr(global.jplopsoft_STATUS_INVALID_PARAMETER||0xC000000D,msg||'Invalid D3DX parameter.');}
function iv(v,d){v=parseInt(v,10);return isNaN(v)?(d||0):v;}
function nv(v,d){v=Number(v);return isFinite(v)?v:(d||0);}
function state(ctx){if(!ctx.d3dx)ctx.d3dx={objects:{},count:0,maxObjects:4096,renderers:{},textureBytes:0,maxTextureBytes:128*1024*1024};return ctx.d3dx;}
function key(v){v=String(v||'');if(!/^t[0-9]+$/.test(v))throw param('Invalid three32 object id.');return v;}
function put(ctx,id,type,o){var s=state(ctx),k=key(id);if(s.objects[k])throw param('three32 object id already exists.');if(s.count>=s.maxObjects)throw quota('three32 live-object quota exceeded.');s.objects[k]={id:k,type:type,obj:o};s.count++;return k;}
function entry(ctx,id){var e=state(ctx).objects[String(id||'')];if(!e)throw invalid('three32 object not found: '+String(id||''));return e;}
function ownedWindow(ctx,hwnd){return !!(ctx&&ctx.windows&&ctx.windows[String(iv(hwnd))]);}
function client(hwnd){return typeof global.jplopsoft_GetClientElement==='function'?global.jplopsoft_GetClientElement(iv(hwnd)):null;}
function ensureThree(){if(global.THREE&&typeof global.THREE.Scene==='function')return Promise.resolve(global.THREE);return new Promise(function(resolve,reject){if(typeof global.jplopsoft_loadOptionalMirroredScript!=='function'){reject(unsupported('Three.js loader is unavailable.'));return;}global.jplopsoft_loadOptionalMirroredScript('three',function(err){if(err||!global.THREE){reject(unsupported('three.min.js could not be loaded.'));return;}resolve(global.THREE);});});}
function ctor(T,type,args){args=Array.isArray(args)?args:[];switch(type){case'Scene':return new T.Scene();case'Group':return new T.Group();case'Object3D':return new T.Object3D();case'PerspectiveCamera':return new T.PerspectiveCamera(nv(args[0],50),nv(args[1],1),nv(args[2],.1),nv(args[3],2000));case'OrthographicCamera':return new T.OrthographicCamera(nv(args[0],-1),nv(args[1],1),nv(args[2],1),nv(args[3],-1),nv(args[4],.1),nv(args[5],2000));case'BoxGeometry':return new T.BoxGeometry(nv(args[0],1),nv(args[1],1),nv(args[2],1),iv(args[3],1),iv(args[4],1),iv(args[5],1));case'SphereGeometry':return new T.SphereGeometry(nv(args[0],1),iv(args[1],32),iv(args[2],16));case'PlaneGeometry':return new T.PlaneGeometry(nv(args[0],1),nv(args[1],1),iv(args[2],1),iv(args[3],1));case'CylinderGeometry':return new T.CylinderGeometry(nv(args[0],1),nv(args[1],1),nv(args[2],1),iv(args[3],32));case'TorusGeometry':return new T.TorusGeometry(nv(args[0],1),nv(args[1],.4),iv(args[2],16),iv(args[3],48));case'BufferGeometry':return new T.BufferGeometry();case'Float32BufferAttribute':return new T.Float32BufferAttribute(Array.isArray(args[0])?args[0]:[],iv(args[1],3),!!args[2]);case'Uint16BufferAttribute':return new T.Uint16BufferAttribute(Array.isArray(args[0])?args[0]:[],iv(args[1],1),!!args[2]);case'MeshBasicMaterial':return new T.MeshBasicMaterial(args[0]||{});case'MeshStandardMaterial':return new T.MeshStandardMaterial(args[0]||{});case'MeshPhongMaterial':return new T.MeshPhongMaterial(args[0]||{});case'LineBasicMaterial':return new T.LineBasicMaterial(args[0]||{});case'PointsMaterial':return new T.PointsMaterial(args[0]||{});case'AmbientLight':return new T.AmbientLight(args[0]===undefined?0xffffff:args[0],nv(args[1],1));case'DirectionalLight':return new T.DirectionalLight(args[0]===undefined?0xffffff:args[0],nv(args[1],1));case'PointLight':return new T.PointLight(args[0]===undefined?0xffffff:args[0],nv(args[1],1),nv(args[2],0),nv(args[3],2));case'AxesHelper':return new T.AxesHelper(nv(args[0],1));case'GridHelper':return new T.GridHelper(nv(args[0],10),iv(args[1],10),args[2]===undefined?0x444444:args[2],args[3]===undefined?0x888888:args[3]);default:throw unsupported('Unsupported three32 constructor: '+type);}}
function rendererSurface(ctx,id,opt,T){opt=opt||{};var hwnd=iv(opt.hwnd),el,cv,r,ro;if(!ownedWindow(ctx,hwnd))throw invalid('three32 renderer HWND does not belong to this process.');el=client(hwnd);if(!el)throw invalid('Window client area unavailable.');cv=document.createElement('canvas');cv.className='jplopsoft-three32-surface';cv.setAttribute('data-three32-id',String(id));cv.style.cssText='position:absolute;inset:0;width:100%;height:100%;display:block;pointer-events:none;z-index:0;';try{if(global.getComputedStyle(el).position==='static')el.style.position='relative';}catch(ignore){}if(el.firstChild)el.insertBefore(cv,el.firstChild);else el.appendChild(cv);r=new T.WebGLRenderer({canvas:cv,antialias:opt.antialias!==false,alpha:!!opt.alpha,preserveDrawingBuffer:!!opt.preserveDrawingBuffer,powerPreference:String(opt.powerPreference||'high-performance')});r.setPixelRatio(Math.max(1,Math.min(4,nv(opt.pixelRatio,Number(global.devicePixelRatio)||1))));var rec={renderer:r,canvas:cv,client:el,hwnd:hwnd,observer:null,autoSize:opt.autoSize!==false};function resize(){if(!rec.autoSize)return;var box=el.getBoundingClientRect();r.setSize(Math.max(1,Math.round(box.width)),Math.max(1,Math.round(box.height)),false);}resize();if(typeof ResizeObserver==='function'){ro=new ResizeObserver(resize);try{ro.observe(el);}catch(ignoreObs){}rec.observer=ro;}return rec;}
function safePath(path){path=String(path||'');if(!path||path.length>128||/(?:__proto__|prototype|constructor)/.test(path))throw param('Unsafe three32 property path.');return path.split('.');}
function setProp(o,path,value){var parts=safePath(path),t=o,i;for(i=0;i<parts.length-1;i++){if(!t||typeof t!=='object')throw param('Invalid three32 property path.');t=t[parts[i]];}var last=parts[parts.length-1];if(!t||typeof t!=='object'||typeof t[last]==='function')throw param('Property cannot be assigned.');if(t[last]&&t[last].isColor&&typeof t[last].set==='function'){t[last].set(value);return true;}t[last]=value;return true;}
function disposeEntry(ctx,e){var s=state(ctx),o=e.obj;try{if(e.type==='WebGLRenderer'){if(o.observer)o.observer.disconnect();if(o.renderer)o.renderer.dispose();if(o.renderer&&o.renderer.forceContextLoss)o.renderer.forceContextLoss();if(o.canvas&&o.canvas.parentNode)o.canvas.parentNode.removeChild(o.canvas);}else{if(o&&typeof o.dispose==='function')o.dispose();}}catch(ignore){}delete s.objects[e.id];s.count=Math.max(0,s.count-1);}
function cleanup(ctx){var s=ctx&&ctx.d3dx;if(!s)return;Object.keys(s.objects).forEach(function(k){var e=s.objects[k];if(e)disposeEntry(ctx,e);});ctx.d3dx=null;}
var METHODS={lookAt:1,rotateX:1,rotateY:1,rotateZ:1,translateX:1,translateY:1,translateZ:1,updateProjectionMatrix:1,updateMatrix:1,updateMatrixWorld:1,computeVertexNormals:1,computeBoundingBox:1,computeBoundingSphere:1,center:1,clear:1};
async function dispatch(ctx,method,args){args=args||[];var T=await ensureThree(),e,o,id,type,a,i,rec,children;
if(method==='GetVersion')return{version:API.version,model:API.model,threeRevision:String(T.REVISION||''),backend:'Three.js/WebGL'};
if(method==='CreateObject'){id=key(args[0]);type=String(args[1]||'');a=Array.isArray(args[2])?args[2]:[];o=ctor(T,type,a);put(ctx,id,type,o);return id;}
if(method==='CreateMesh'||method==='CreateLine'||method==='CreatePoints'){id=key(args[0]);var ge=entry(ctx,args[1]).obj,ma=entry(ctx,args[2]).obj;if(method==='CreateMesh')o=new T.Mesh(ge,ma);else if(method==='CreateLine')o=new T.Line(ge,ma);else o=new T.Points(ge,ma);put(ctx,id,method.substring(6),o);return id;}
if(method==='CreateRenderer'){id=key(args[0]);rec=rendererSurface(ctx,id,args[1]||{},T);put(ctx,id,'WebGLRenderer',rec);return id;}
if(method==='DisposeObject'){e=entry(ctx,args[0]);disposeEntry(ctx,e);return true;}
if(method==='Add'){o=entry(ctx,args[0]).obj;children=Array.isArray(args[1])?args[1]:[args[1]];for(i=0;i<children.length;i++)o.add(entry(ctx,children[i]).obj);return true;}
if(method==='Remove'){o=entry(ctx,args[0]).obj;children=Array.isArray(args[1])?args[1]:[args[1]];for(i=0;i<children.length;i++)o.remove(entry(ctx,children[i]).obj);return true;}
if(method==='SetVector3'){o=entry(ctx,args[0]).obj;var v=o[String(args[1]||'')];if(!v||typeof v.set!=='function')throw param('Vector3 property not found.');v.set(nv(args[2]),nv(args[3]),nv(args[4]));return true;}
if(method==='SetEuler'){o=entry(ctx,args[0]).obj;v=o[String(args[1]||'')];if(!v||typeof v.set!=='function')throw param('Euler property not found.');v.set(nv(args[2]),nv(args[3]),nv(args[4]),args[5]?String(args[5]):v.order);return true;}
if(method==='SetQuaternion'){o=entry(ctx,args[0]).obj;v=o[String(args[1]||'')];if(!v||typeof v.set!=='function')throw param('Quaternion property not found.');v.set(nv(args[2]),nv(args[3]),nv(args[4]),nv(args[5],1));return true;}
if(method==='SetProperty'){o=entry(ctx,args[0]).obj;return setProp(o,args[1],args[2]);}
if(method==='GetProperty'){o=entry(ctx,args[0]).obj;var parts=safePath(args[1]),x=o;for(i=0;i<parts.length;i++){x=x[parts[i]];}if(typeof x==='number'||typeof x==='string'||typeof x==='boolean'||x===null)return x;if(x&&x.isVector3)return{x:x.x,y:x.y,z:x.z};if(x&&x.isEuler)return{x:x.x,y:x.y,z:x.z,order:x.order};if(x&&x.isColor)return x.getHex();return null;}
if(method==='CallMethod'){o=entry(ctx,args[0]).obj;var mn=String(args[1]||'');if(!METHODS[mn]||typeof o[mn]!=='function')throw unsupported('three32 method is not exposed: '+mn);var ca=Array.isArray(args[2])?args[2]:[];o[mn].apply(o,ca);return true;}
if(method==='GeometrySetAttribute'){o=entry(ctx,args[0]).obj;o.setAttribute(String(args[1]||''),entry(ctx,args[2]).obj);return true;}
if(method==='GeometrySetIndex'){o=entry(ctx,args[0]).obj;var idx=args[1];if(typeof idx==='string'&&state(ctx).objects[idx])idx=entry(ctx,idx).obj;o.setIndex(idx);return true;}
if(method==='MaterialSetTexture'){o=entry(ctx,args[0]).obj;var prop=String(args[1]||'map');if(!/^(map|normalMap|roughnessMap|metalnessMap|emissiveMap|alphaMap|aoMap)$/.test(prop))throw param('Unsupported material texture property.');o[prop]=entry(ctx,args[2]).obj;o.needsUpdate=true;return true;}
if(method==='RendererSetSize'){e=entry(ctx,args[0]);if(e.type!=='WebGLRenderer')throw invalid('Not a renderer.');e.obj.autoSize=false;e.obj.renderer.setSize(Math.max(1,iv(args[1],1)),Math.max(1,iv(args[2],1)),false);return true;}
if(method==='RendererSetPixelRatio'){e=entry(ctx,args[0]);e.obj.renderer.setPixelRatio(Math.max(1,Math.min(4,nv(args[1],1))));return true;}
if(method==='RendererSetClearColor'){e=entry(ctx,args[0]);e.obj.renderer.setClearColor(args[1]===undefined?0x000000:args[1],args[2]===undefined?1:nv(args[2],1));return true;}
if(method==='RendererRender'){e=entry(ctx,args[0]);var scene=entry(ctx,args[1]).obj,cam=entry(ctx,args[2]).obj;e.obj.renderer.render(scene,cam);return true;}
if(method==='RendererClear'){e=entry(ctx,args[0]);e.obj.renderer.clear(args[1]!==false,args[2]!==false,!!args[3]);return true;}
if(method==='RendererGetSize'){e=entry(ctx,args[0]);var vv=new T.Vector2();e.obj.renderer.getSize(vv);return{width:vv.x,height:vv.y,pixelRatio:e.obj.renderer.getPixelRatio()};}
if(method==='LoadTexture'){id=key(args[0]);var url=String(args[1]||'');if(url.indexOf('data:image/')!==0||url.length>24*1024*1024)throw param('three32 TextureLoader accepts image data URLs up to 24 MiB only.');var texture=await new Promise(function(resolve,reject){new T.TextureLoader().load(url,resolve,undefined,function(er){reject(param('Texture decode failed: '+String(er&&er.message||er||'')));});});put(ctx,id,'Texture',texture);return id;}
throw unsupported('Unsupported d3dx.dll API: '+method);
}
global.jplopsoft_D3DX=API;
global.jplopsoft_d3dxDispatch=dispatch;
global.jplopsoft_d3dxCleanupContext=cleanup;
})(window);
