/* ExOS built-in XSH applications
 * Version: 6.4.0-dev-os31
 * Requires: exos.js 6.4.0-dev-os31
 * V8-only client module.
 */
(function(global){
'use strict';
global.jplopsoft_EXOS_XSH_APPS=Object.freeze({version:"6.4.0-dev-os31",format:'EXOS_XSH_APPS_V1',apps:Object.freeze({
calc:Object.freeze({id:'calc',fileName:'calc.xsh',title:'小算盤',description:'ExOS Calculator (.xsh)',icon:'calc',singleInstance:true,source:"const hwnd=await user32.CreateWindow({title:'\u5c0f\u7b97\u76e4',icon:'calc',width:390,height:580});\nawait user32.CreateControl(hwnd,{type:'input',id:'display',text:'0',readOnly:true,style:{width:'100%',height:'64px',fontSize:'30px',textAlign:'right',boxSizing:'border-box',marginBottom:'8px'}});\nawait user32.CreateControl(hwnd,{type:'div',id:'grid',style:{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'6px',width:'100%'}});\nlet input='0',acc=null,op='',waiting=false;const fmt=n=>Number.isFinite(n)?String(parseFloat(Number(n).toPrecision(14))):'Error';const show=()=>user32.SetControlText('display',input);const value=()=>Number(input)||0;const bin=(a,b,o)=>o==='+'?a+b:o==='-'?a-b:o==='*'?a*b:o==='/'?(b===0?NaN:a/b):b;\nconst press=async a=>{if(/^\\d$/.test(a)){input=waiting?a:(input==='0'?a:input+a);waiting=false;}else if(a==='.'){if(waiting){input='0.';waiting=false;}else if(!input.includes('.'))input+='.';}else if(a==='C'){input='0';acc=null;op='';waiting=false;}else if(a==='\u00b1'){input=fmt(-value());}else if(a==='\u221a'){input=fmt(Math.sqrt(value()));waiting=true;}else if(['+','-','*','/'].includes(a)){if(acc===null)acc=value();else if(op&&!waiting){acc=bin(acc,value(),op);input=fmt(acc);}op=a;waiting=true;}else if(a==='='){if(op&&acc!==null){input=fmt(bin(acc,value(),op));acc=Number(input);op='';waiting=true;}}await show();};\nfor(const [text,action] of [['C','C'],['\u00b1','\u00b1'],['\u221a','\u221a'],['\u00f7','/'],['7','7'],['8','8'],['9','9'],['\u00d7','*'],['4','4'],['5','5'],['6','6'],['\u2212','-'],['1','1'],['2','2'],['3','3'],['+','+'],['0','0'],['.','.'],['=','=']]){const id='k_'+action.replace(/[^a-z0-9]/gi,c=>c.charCodeAt(0));await user32.CreateControl(hwnd,{type:'button',id,parentId:'grid',text,style:{height:'54px',fontSize:'18px',margin:'0'}});user32.OnControl(id,()=>press(action));}"}),
calendar:Object.freeze({id:'calendar',fileName:'calendar.xsh',title:'日曆',description:'ExOS Calendar (.xsh)',icon:'calendar',singleInstance:true,source:"const hwnd=await user32.CreateWindow({title:'\u65e5\u66c6',icon:'calendar',width:430,height:470});await user32.CreateControl(hwnd,{type:'div',id:'nav',style:{display:'flex',gap:'6px',alignItems:'center'}});await user32.CreateControl(hwnd,{type:'button',id:'prev',parentId:'nav',text:'\u2039',style:{width:'42px'}});await user32.CreateControl(hwnd,{type:'button',id:'today',parentId:'nav',text:'\u4eca\u5929'});await user32.CreateControl(hwnd,{type:'button',id:'next',parentId:'nav',text:'\u203a',style:{width:'42px'}});await user32.CreateControl(hwnd,{type:'label',id:'month',style:{fontSize:'20px',fontWeight:'600',margin:'12px 0 6px'}});await user32.CreateControl(hwnd,{type:'pre',id:'cal',style:{fontSize:'16px',lineHeight:'1.8',background:'#fff',color:'#111827',border:'1px solid #cbd5e1',padding:'12px',margin:'0'}});let d=new Date(),y=d.getFullYear(),m=d.getMonth();const render=async()=>{const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();let s='\u65e5  \u4e00  \u4e8c  \u4e09  \u56db  \u4e94  \u516d\\n',w=first.getDay();s+='    '.repeat(w);for(let day=1;day<=days;day++){s+=String(day).padStart(2,' ')+'  ';if((w+day)%7===0)s+='\\n';}await user32.SetControlText('month',`${y} \u5e74 ${m+1} \u6708`);await user32.SetControlText('cal',s);};user32.OnControl('prev',async()=>{if(--m<0){m=11;y--;}await render();});user32.OnControl('next',async()=>{if(++m>11){m=0;y++;}await render();});user32.OnControl('today',async()=>{d=new Date();y=d.getFullYear();m=d.getMonth();await render();});await render();"}),
html_editor:Object.freeze({id:'html_editor',fileName:'html_editor.xsh',title:'HTML 編輯器',description:'ExOS HTML Editor (.xsh)',icon:'html',singleInstance:false,source:"const path=process.argv[1];if(!path)throw new Error('HTML editor requires a file path.');const src=await kernel32.ReadTextFile(path);const hwnd=await user32.CreateWindow({title:'HTML \u7de8\u8f2f\u5668 - '+path.split('\\\\').pop(),icon:'html',width:980,height:700});await user32.CreateControl(hwnd,{type:'div',id:'bar',style:{display:'flex',gap:'6px',marginBottom:'6px'}});await user32.CreateControl(hwnd,{type:'button',id:'save',parentId:'bar',text:'\u5132\u5b58'});await user32.CreateControl(hwnd,{type:'button',id:'preview',parentId:'bar',text:'\u9810\u89bd'});await user32.CreateControl(hwnd,{type:'button',id:'image',parentId:'bar',text:'\u63d2\u5165 Base64 \u5716\u7247'});await user32.CreateControl(hwnd,{type:'textarea',id:'source',text:src,style:{width:'100%',height:'calc(100% - 52px)',boxSizing:'border-box',fontFamily:'Consolas,monospace',fontSize:'13px',resize:'none',margin:'0'}});user32.OnControl('save',async()=>{const text=await user32.GetControlText('source');await kernel32.WriteTextFile(path,text);await user32.MessageBox('\u5df2\u5132\u5b58\u81f3 ExFS\u3002','HTML \u7de8\u8f2f\u5668');});user32.OnControl('preview',async()=>{const text=await user32.GetControlText('source');const p=await user32.CreateWindow({title:'HTML \u9810\u89bd - '+path.split('\\\\').pop(),icon:'html',width:820,height:620});await user32.CreateControl(p,{type:'htmlpreview',id:'preview_'+p,html:text,style:{width:'100%',height:'100%',border:'0',margin:'0'}});});user32.OnControl('image',async()=>{const f=await user32.PickImageDataUrl();if(!f)return;const alt=String(f.name||'image').replace(/[\"<>]/g,'');await user32.InsertControlText('source',`<img src=\"${f.dataUrl}\" alt=\"${alt}\">`);});"}),
image_viewer:Object.freeze({id:'image_viewer',fileName:'image_viewer.xsh',title:'圖片預覽',description:'ExOS Image Viewer (.xsh)',icon:'file',singleInstance:false,source:"const path=process.argv[1];if(!path)throw new Error('Image viewer requires a file path.');const h=await kernel32.CreateFile(path,kernel32.GENERIC_READ,kernel32.OPEN_EXISTING);const attr=await kernel32.GetFileAttributes(path);const r=await kernel32.ReadFile(h,Math.min((attr&&attr.size)||8388608,8388608),0);await kernel32.CloseHandle(h);const bytes=new Uint8Array(r.data||[]);const ext=(path.split('.').pop()||'').toLowerCase();const mime=ext==='png'?'image/png':ext==='gif'?'image/gif':ext==='webp'?'image/webp':'image/jpeg';let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const url=`data:${mime};base64,${btoa(bin)}`;const hwnd=await user32.CreateWindow({title:'\u5716\u7247\u9810\u89bd - '+path.split('\\\\').pop(),icon:'file',width:900,height:680});await user32.CreateControl(hwnd,{type:'image',id:'image',src:url,alt:path,style:{display:'block',maxWidth:'100%',maxHeight:'calc(100% - 34px)',margin:'0 auto'}});await user32.CreateControl(hwnd,{type:'label',id:'info',text:`${path} \uff5c ${bytes.length} bytes \uff5c ${mime}`,style:{textAlign:'center',marginTop:'6px'}});"})
})});
})(window);
