/* ExOS d3d11.dll emulation
 * Version: 6.4.0-dev-os65
 * Model: EXOS_D3D11_V1
 * Client: V8-only browsers
 *
 * WebGL2-first Direct3D 11 style graphics ABI for XSH applications.
 * This is an API/semantic emulation, not the Microsoft binary ABI.
 * Shaders are GLSL ES source (not HLSL bytecode).
 */
(function(global){
'use strict';

var API={version:'6.4.0-dev-os65',model:'EXOS_D3D11_V1',ready:true};
var T={DEVICE:'DEVICE',CONTEXT:'CONTEXT',SWAPCHAIN:'SWAPCHAIN',BUFFER:'BUFFER',TEXTURE2D:'TEXTURE2D',RTV:'RTV',DSV:'DSV',SRV:'SRV',VS:'VS',PS:'PS',LAYOUT:'LAYOUT',SAMPLER:'SAMPLER',RASTERIZER:'RASTERIZER',BLEND:'BLEND',DEPTHSTATE:'DEPTHSTATE'};
var BIND={VERTEX:0x1,INDEX:0x2,CONSTANT:0x4,SHADER_RESOURCE:0x8,RENDER_TARGET:0x20,DEPTH_STENCIL:0x40};
var TOPO={POINTLIST:1,LINELIST:2,LINESTRIP:3,TRIANGLELIST:4,TRIANGLESTRIP:5};

function exerr(status,msg){if(typeof global.jplopsoft_xshError==='function')return global.jplopsoft_xshError(status,msg);var e=new Error(msg);e.status=status;return e;}
function invalid(msg){return exerr(global.jplopsoft_STATUS_INVALID_HANDLE||0xC0000008,msg||'Invalid D3D11 handle.');}
function unsupported(msg){return exerr(global.jplopsoft_STATUS_NOT_SUPPORTED||0xC00000BB,msg||'D3D11 operation is not supported.');}
function quota(msg){return exerr(global.jplopsoft_STATUS_QUOTA_EXCEEDED||0xC0000044,msg||'D3D11 resource quota exceeded.');}
function param(msg){return exerr(global.jplopsoft_STATUS_INVALID_PARAMETER||0xC000000D,msg||'Invalid D3D11 parameter.');}
function iv(v,d){v=parseInt(v,10);return isNaN(v)?(d||0):v;}
function nv(v,d){v=Number(v);return isFinite(v)?v:(d||0);}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function ownWindow(ctx,hwnd){return !!(ctx&&ctx.windows&&ctx.windows[String(iv(hwnd))]);}
function client(hwnd){return typeof global.jplopsoft_GetClientElement==='function'?global.jplopsoft_GetClientElement(iv(hwnd)):null;}
function state(ctx){if(!ctx.d3d11)ctx.d3d11={next:0x6000,objects:{},surfaces:{},objectCount:0,bufferBytes:0,textureBytes:0,maxObjects:4096,maxBufferBytes:256*1024*1024,maxTextureBytes:512*1024*1024};return ctx.d3d11;}
function alloc(ctx,type,o){var s=state(ctx),h;if(s.objectCount>=s.maxObjects)throw quota('D3D11 live-object quota exceeded.');h=s.next++;while(s.objects[String(h)])h=s.next++;o=o||{};o.type=type;o.handle=h;s.objects[String(h)]=o;s.objectCount++;return h;}
function obj(ctx,h,type){var o=state(ctx).objects[String(iv(h))]||null;if(!o||(type&&o.type!==type))throw invalid('Invalid '+String(type||'D3D11')+' handle.');return o;}
function deviceOf(ctx,h){return obj(ctx,h,T.DEVICE);}
function contextOf(ctx,h){return obj(ctx,h,T.CONTEXT);}
function resourceBytes(desc,kind){if(kind==='buffer')return Math.max(0,iv(desc&&desc.byteWidth));var w=Math.max(1,iv(desc&&desc.width,1)),h=Math.max(1,iv(desc&&desc.height,1));return w*h*4;}
function typed(data,format){if(data===undefined||data===null)return null;if(ArrayBuffer.isView(data))return data;if(data instanceof ArrayBuffer)return new Uint8Array(data);var a=Array.isArray(data)?data:[];format=String(format||'FLOAT32').toUpperCase();if(format==='UINT16'||format==='R16_UINT')return new Uint16Array(a);if(format==='UINT32'||format==='R32_UINT')return new Uint32Array(a);if(format==='INT16')return new Int16Array(a);if(format==='INT32')return new Int32Array(a);if(format==='UINT8'||format==='RGBA8'||format==='R8G8B8A8_UNORM')return new Uint8Array(a);return new Float32Array(a);}
function usage(gl,desc){var u=String(desc&&desc.usage||'DEFAULT').toUpperCase();return u==='DYNAMIC'?gl.DYNAMIC_DRAW:(u==='IMMUTABLE'?gl.STATIC_DRAW:gl.STATIC_DRAW);}
function shaderType(gl,kind){return kind===T.VS?gl.VERTEX_SHADER:gl.FRAGMENT_SHADER;}
function compile(gl,kind,source){var sh=gl.createShader(shaderType(gl,kind));if(!sh)throw unsupported('WebGL shader allocation failed.');gl.shaderSource(sh,String(source||''));gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS)){var log=gl.getShaderInfoLog(sh)||'Shader compilation failed.';gl.deleteShader(sh);throw param(log);}return sh;}
function glType(gl,name){name=String(name||'FLOAT').toUpperCase();if(name==='UNSIGNED_BYTE'||name==='UINT8')return gl.UNSIGNED_BYTE;if(name==='BYTE'||name==='INT8')return gl.BYTE;if(name==='UNSIGNED_SHORT'||name==='UINT16'||name==='R16_UINT')return gl.UNSIGNED_SHORT;if(name==='SHORT'||name==='INT16')return gl.SHORT;if(name==='UNSIGNED_INT'||name==='UINT32'||name==='R32_UINT')return gl.UNSIGNED_INT;if(name==='INT'||name==='INT32')return gl.INT;return gl.FLOAT;}
function topology(gl,t){t=iv(t,TOPO.TRIANGLELIST);if(t===TOPO.POINTLIST)return gl.POINTS;if(t===TOPO.LINELIST)return gl.LINES;if(t===TOPO.LINESTRIP)return gl.LINE_STRIP;if(t===TOPO.TRIANGLESTRIP)return gl.TRIANGLE_STRIP;return gl.TRIANGLES;}
function canvasSurface(ctx,hwnd,desc){var s=state(ctx),key=String(iv(hwnd)),sf=s.surfaces[key],el,cv,attrs,gl;if(!ownWindow(ctx,hwnd))throw invalid('Swap chain HWND does not belong to the XSH process.');if(sf&&sf.canvas&&sf.canvas.isConnected)return sf;el=client(hwnd);if(!el)throw invalid('Window client area is unavailable.');cv=document.createElement('canvas');cv.className='jplopsoft-d3d11-surface';cv.setAttribute('data-exos-d3d11-hwnd',key);cv.style.cssText='position:absolute;inset:0;width:100%;height:100%;display:block;pointer-events:none;z-index:0;background:transparent;';try{if(global.getComputedStyle(el).position==='static')el.style.position='relative';}catch(ignore){}if(el.firstChild)el.insertBefore(cv,el.firstChild);else el.appendChild(cv);
attrs={alpha:desc&&desc.alpha!==false,antialias:desc&&desc.antialias!==false,depth:desc&&desc.depth!==false,stencil:!!(desc&&desc.stencil),premultipliedAlpha:false,preserveDrawingBuffer:!!(desc&&desc.preserveDrawingBuffer),powerPreference:String(desc&&desc.powerPreference||'high-performance')};
gl=cv.getContext('webgl2',attrs);var webgl2=!!gl;if(!gl)gl=cv.getContext('webgl',attrs)||cv.getContext('experimental-webgl',attrs);if(!gl){try{cv.parentNode.removeChild(cv);}catch(ignoreRemove){}throw unsupported('WebGL is unavailable.');}
sf={ctx:ctx,hwnd:iv(hwnd),client:el,canvas:cv,gl:gl,webgl2:webgl2,dpr:1,width:1,height:1,observer:null};resizeSurface(sf,desc&&desc.width,desc&&desc.height);
if(typeof ResizeObserver==='function'){sf.observer=new ResizeObserver(function(){resizeSurface(sf);});try{sf.observer.observe(el);}catch(ignoreObs){}}
s.surfaces[key]=sf;return sf;}
function resizeSurface(sf,w,h){if(!sf||!sf.canvas)return;var r=sf.client&&sf.client.getBoundingClientRect?sf.client.getBoundingClientRect():{width:sf.canvas.clientWidth||1,height:sf.canvas.clientHeight||1};var cssW=Math.max(1,iv(w)||Math.round(r.width)||1),cssH=Math.max(1,iv(h)||Math.round(r.height)||1),dpr=clamp(Number(global.devicePixelRatio)||1,1,4),rw=Math.max(1,Math.round(cssW*dpr)),rh=Math.max(1,Math.round(cssH*dpr));if(sf.canvas.width!==rw)sf.canvas.width=rw;if(sf.canvas.height!==rh)sf.canvas.height=rh;sf.canvas.style.width=cssW+'px';sf.canvas.style.height=cssH+'px';sf.width=cssW;sf.height=cssH;sf.dpr=dpr;try{sf.gl.viewport(0,0,rw,rh);}catch(ignoreVp){}return{width:cssW,height:cssH,pixelWidth:rw,pixelHeight:rh,dpr:dpr};}
function offscreenSurface(desc){var cv=document.createElement('canvas');cv.width=Math.max(1,iv(desc&&desc.width,1));cv.height=Math.max(1,iv(desc&&desc.height,1));var attrs={alpha:true,antialias:true,depth:true,stencil:false,premultipliedAlpha:false};var gl=cv.getContext('webgl2',attrs),w2=!!gl;if(!gl)gl=cv.getContext('webgl',attrs)||cv.getContext('experimental-webgl',attrs);if(!gl)throw unsupported('WebGL is unavailable.');return{canvas:cv,gl:gl,webgl2:w2,dpr:1,width:cv.width,height:cv.height,offscreen:true};}
function deviceBundle(ctx,sf){var gl=sf.gl,dh,ch;dh=alloc(ctx,T.DEVICE,{surface:sf,gl:gl,webgl2:sf.webgl2,programs:{},lost:false});ch=alloc(ctx,T.CONTEXT,{device:dh,gl:gl,state:{layout:0,vertexBuffers:[],indexBuffer:null,topology:TOPO.TRIANGLELIST,vs:0,ps:0,rtvs:[],dsv:0,viewport:null,resources:[],samplers:[],uniforms:{},rasterizer:0,blend:0,depthState:0}});obj(ctx,dh,T.DEVICE).immediateContext=ch;return{device:dh,context:ch,featureLevel:sf.webgl2?'D3D_FEATURE_LEVEL_11_0':'D3D_FEATURE_LEVEL_9_3',driverType:'D3D_DRIVER_TYPE_HARDWARE'};}
function bindTarget(ctx,c){var gl=c.gl,rtv=c.state.rtvs&&c.state.rtvs.length?obj(ctx,c.state.rtvs[0],T.RTV):null;if(rtv&&rtv.framebuffer)gl.bindFramebuffer(gl.FRAMEBUFFER,rtv.framebuffer);else gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
function ensureProgram(ctx,c){var d=obj(ctx,c.device,T.DEVICE),vs=obj(ctx,c.state.vs,T.VS),ps=obj(ctx,c.state.ps,T.PS),key=String(vs.handle)+':'+String(ps.handle),p=d.programs[key];if(p)return p;var gl=c.gl,prog=gl.createProgram();gl.attachShader(prog,vs.shader);gl.attachShader(prog,ps.shader);gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS)){var log=gl.getProgramInfoLog(prog)||'Program link failed.';gl.deleteProgram(prog);throw param(log);}p={program:prog,uniforms:{}};d.programs[key]=p;return p;}
function setUniform(gl,prog,name,val){var loc=prog.uniforms[name];if(loc===undefined){loc=gl.getUniformLocation(prog.program,name);prog.uniforms[name]=loc;}if(loc===null)return false;var type='',v=val;if(v&&typeof v==='object'&&!Array.isArray(v)&&!ArrayBuffer.isView(v)&&v.value!==undefined){type=String(v.type||'').toLowerCase();v=v.value;}if(typeof v==='number'){if(type==='int'||type==='sampler'||type==='bool')gl.uniform1i(loc,iv(v));else gl.uniform1f(loc,Number(v));return true;}var a=ArrayBuffer.isView(v)?v:Array.isArray(v)?v:[];if(type==='mat4'||a.length===16){gl.uniformMatrix4fv(loc,false,new Float32Array(a));return true;}if(type==='mat3'||a.length===9){gl.uniformMatrix3fv(loc,false,new Float32Array(a));return true;}if(type==='int2'){gl.uniform2iv(loc,new Int32Array(a));return true;}if(type==='int3'){gl.uniform3iv(loc,new Int32Array(a));return true;}if(type==='int4'){gl.uniform4iv(loc,new Int32Array(a));return true;}if(a.length===4){gl.uniform4fv(loc,new Float32Array(a));return true;}if(a.length===3){gl.uniform3fv(loc,new Float32Array(a));return true;}if(a.length===2){gl.uniform2fv(loc,new Float32Array(a));return true;}if(a.length===1){gl.uniform1fv(loc,new Float32Array(a));return true;}return false;}
function applyStates(ctx,c){var gl=c.gl,rs=c.state.rasterizer?obj(ctx,c.state.rasterizer,T.RASTERIZER):null,bd=c.state.blend?obj(ctx,c.state.blend,T.BLEND):null,ds=c.state.depthState?obj(ctx,c.state.depthState,T.DEPTHSTATE):null,d;
  d=rs&&rs.desc||{};var cm=String(d.cullMode||'BACK').toUpperCase();if(cm==='NONE')gl.disable(gl.CULL_FACE);else{gl.enable(gl.CULL_FACE);gl.cullFace(cm==='FRONT'?gl.FRONT:gl.BACK);gl.frontFace(d.frontCounterClockwise?gl.CCW:gl.CW);}
  d=bd&&bd.desc||{};if(d.enabled){gl.enable(gl.BLEND);gl.blendFunc(blendValue(gl,d.srcBlend||'SRC_ALPHA'),blendValue(gl,d.destBlend||'INV_SRC_ALPHA'));}else gl.disable(gl.BLEND);
  d=ds&&ds.desc||{};var depthOn=ds?d.depthEnable!==false:!!c.state.dsv;if(depthOn){gl.enable(gl.DEPTH_TEST);gl.depthMask(d.depthWriteMask!==false);var fn=String(d.depthFunc||'LESS').toUpperCase(),gf=fn==='LEQUAL'?gl.LEQUAL:(fn==='GREATER'?gl.GREATER:(fn==='GEQUAL'?gl.GEQUAL:(fn==='ALWAYS'?gl.ALWAYS:gl.LESS)));gl.depthFunc(gf);}else gl.disable(gl.DEPTH_TEST);
}
function blendValue(gl,n){n=String(n||'ONE').toUpperCase();if(n==='ZERO')return gl.ZERO;if(n==='SRC_ALPHA')return gl.SRC_ALPHA;if(n==='INV_SRC_ALPHA')return gl.ONE_MINUS_SRC_ALPHA;if(n==='DEST_ALPHA')return gl.DST_ALPHA;if(n==='INV_DEST_ALPHA')return gl.ONE_MINUS_DST_ALPHA;if(n==='SRC_COLOR')return gl.SRC_COLOR;if(n==='INV_SRC_COLOR')return gl.ONE_MINUS_SRC_COLOR;if(n==='DEST_COLOR')return gl.DST_COLOR;if(n==='INV_DEST_COLOR')return gl.ONE_MINUS_DST_COLOR;return gl.ONE;}
function applyPipeline(ctx,c){var gl=c.gl;if(!c.state.vs||!c.state.ps)throw param('Both vertex and pixel shaders must be bound before Draw.');bindTarget(ctx,c);var pr=ensureProgram(ctx,c);gl.useProgram(pr.program);applyStates(ctx,c);var k;for(k in c.state.uniforms)if(c.state.uniforms.hasOwnProperty(k))setUniform(gl,pr,k,c.state.uniforms[k]);var i,srv,samp;for(i=0;i<c.state.resources.length;i++){if(!c.state.resources[i])continue;srv=obj(ctx,c.state.resources[i],T.SRV);gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,obj(ctx,srv.resource,T.TEXTURE2D).texture);if(c.state.samplers[i]&&gl.bindSampler){samp=obj(ctx,c.state.samplers[i],T.SAMPLER);gl.bindSampler(i,samp.sampler);}}
var layout=c.state.layout?obj(ctx,c.state.layout,T.LAYOUT):null;if(layout){for(i=0;i<layout.elements.length;i++){var e=layout.elements[i],slot=iv(e.inputSlot),vb=c.state.vertexBuffers[slot];if(!vb)continue;var bo=obj(ctx,vb.buffer,T.BUFFER);gl.bindBuffer(gl.ARRAY_BUFFER,bo.buffer);var loc=e.location!==undefined?iv(e.location):i;gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,Math.max(1,Math.min(4,iv(e.size,3))),glType(gl,e.type),!!e.normalized,iv(vb.stride)||iv(e.stride),iv(vb.offset)+iv(e.offset));}}
if(c.state.indexBuffer){var ib=obj(ctx,c.state.indexBuffer.buffer,T.BUFFER);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib.buffer);}var vp=c.state.viewport;if(vp)gl.viewport(Math.round(nv(vp.x)*((obj(ctx,c.device,T.DEVICE).surface.dpr)||1)),Math.round(nv(vp.y)*((obj(ctx,c.device,T.DEVICE).surface.dpr)||1)),Math.max(1,Math.round(nv(vp.width)*((obj(ctx,c.device,T.DEVICE).surface.dpr)||1))),Math.max(1,Math.round(nv(vp.height)*((obj(ctx,c.device,T.DEVICE).surface.dpr)||1))));return pr;}
function deleteObject(ctx,o){var s=state(ctx),gl=o.gl,dev;if(!gl&&o.device){dev=s.objects[String(o.device)];if(dev)gl=dev.gl;}try{if(o.type===T.BUFFER&&o.buffer)gl.deleteBuffer(o.buffer);else if(o.type===T.TEXTURE2D&&o.texture)gl.deleteTexture(o.texture);else if((o.type===T.VS||o.type===T.PS)&&o.shader)gl.deleteShader(o.shader);else if(o.type===T.RTV&&o.framebuffer)gl.deleteFramebuffer(o.framebuffer);else if(o.type===T.SAMPLER&&o.sampler&&gl.deleteSampler)gl.deleteSampler(o.sampler);}catch(ignore){}if(o.type===T.BUFFER)s.bufferBytes=Math.max(0,s.bufferBytes-(o.bytes||0));if(o.type===T.TEXTURE2D)s.textureBytes=Math.max(0,s.textureBytes-(o.bytes||0));delete s.objects[String(o.handle)];s.objectCount=Math.max(0,s.objectCount-1);}
function cleanup(ctx){var s=ctx&&ctx.d3d11;if(!s)return;var k,o;for(k in s.objects)if(s.objects.hasOwnProperty(k)){o=s.objects[k];if(o.type===T.DEVICE){try{var pk;for(pk in o.programs)if(o.programs.hasOwnProperty(pk)&&o.programs[pk].program)o.gl.deleteProgram(o.programs[pk].program);}catch(ignorePrograms){}}}var keys=Object.keys(s.objects);for(var i=0;i<keys.length;i++){o=s.objects[keys[i]];if(o)deleteObject(ctx,o);}for(k in s.surfaces)if(s.surfaces.hasOwnProperty(k)){var sf=s.surfaces[k];try{if(sf.observer)sf.observer.disconnect();}catch(ignoreObs){}try{if(sf.gl){var ext=sf.gl.getExtension('WEBGL_lose_context');if(ext)ext.loseContext();}}catch(ignoreLose){}try{if(sf.canvas&&sf.canvas.parentNode)sf.canvas.parentNode.removeChild(sf.canvas);}catch(ignoreCanvas){}}ctx.d3d11=null;}

async function dispatch(ctx,method,args){args=args||[];var s=state(ctx),o,d,c,gl,h,desc,data,bytes,sf,bundle,sc,tex,rtv,view,i;
if(method==='GetVersion')return{version:API.version,model:API.model,backend:'WebGL',shaderLanguage:'GLSL ES'};
if(method==='D3D11CreateDevice'){desc=args[0]||{};sf=offscreenSurface(desc);bundle=deviceBundle(ctx,sf);return bundle;}
if(method==='D3D11CreateDeviceAndSwapChain'){var hwnd=iv(args[0]);desc=args[1]||{};sf=canvasSurface(ctx,hwnd,desc);bundle=deviceBundle(ctx,sf);sc=alloc(ctx,T.SWAPCHAIN,{device:bundle.device,context:bundle.context,hwnd:hwnd,surface:sf,desc:desc});var bb=alloc(ctx,T.TEXTURE2D,{device:bundle.device,kind:'backbuffer',swapChain:sc,width:sf.canvas.width,height:sf.canvas.height,bytes:0});obj(ctx,bundle.device,T.DEVICE).swapChain=sc;return{device:bundle.device,context:bundle.context,swapChain:sc,backBuffer:bb,featureLevel:bundle.featureLevel,driverType:bundle.driverType,width:sf.width,height:sf.height};}
if(method==='GetDeviceInfo'){d=deviceOf(ctx,args[0]);return{featureLevel:d.webgl2?'D3D_FEATURE_LEVEL_11_0':'D3D_FEATURE_LEVEL_9_3',backend:d.webgl2?'WebGL2':'WebGL1',vendor:String(d.gl.getParameter(d.gl.VENDOR)||'WebGL'),renderer:String(d.gl.getParameter(d.gl.RENDERER)||'WebGL'),maxTextureSize:iv(d.gl.getParameter(d.gl.MAX_TEXTURE_SIZE)),maxVertexAttribs:iv(d.gl.getParameter(d.gl.MAX_VERTEX_ATTRIBS)),shaderLanguage:'GLSL ES'};}
if(method==='GetLiveObjectSummary'){var counts={},kk;for(kk in s.objects)if(s.objects.hasOwnProperty(kk)){var t=s.objects[kk].type;counts[t]=(counts[t]||0)+1;}return{objects:s.objectCount,byType:counts,bufferBytes:s.bufferBytes,textureBytes:s.textureBytes};}
if(method==='CreateBuffer'){d=deviceOf(ctx,args[0]);desc=args[1]||{};bytes=resourceBytes(desc,'buffer');if(bytes<=0||bytes>128*1024*1024)throw param('Invalid D3D11 buffer size.');if(s.bufferBytes+bytes>s.maxBufferBytes)throw quota('D3D11 buffer memory quota exceeded.');data=typed(args[2],desc.format);if(data&&data.byteLength>bytes)throw param('Initial buffer data exceeds ByteWidth.');gl=d.gl;var target=(iv(desc.bindFlags)&BIND.INDEX)?gl.ELEMENT_ARRAY_BUFFER:gl.ARRAY_BUFFER;var b=gl.createBuffer();gl.bindBuffer(target,b);if(data)gl.bufferData(target,data,usage(gl,desc));else gl.bufferData(target,bytes,usage(gl,desc));h=alloc(ctx,T.BUFFER,{device:d.handle,gl:gl,buffer:b,target:target,desc:desc,bytes:bytes,shadow:data?Array.prototype.slice.call(data):null,format:String(desc.format||'FLOAT32')});s.bufferBytes+=bytes;return h;}
if(method==='CreateTexture2D'){d=deviceOf(ctx,args[0]);desc=args[1]||{};var w=Math.max(1,iv(desc.width,1)),hh=Math.max(1,iv(desc.height,1));if(w>8192||hh>8192)throw param('Texture dimension exceeds ExOS D3D11 limit.');bytes=w*hh*4;if(s.textureBytes+bytes>s.maxTextureBytes)throw quota('D3D11 texture memory quota exceeded.');gl=d.gl;var gt=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,gt);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,desc.mipLevels>1?gl.LINEAR_MIPMAP_LINEAR:gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);data=typed(args[2],'UINT8');gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,hh,0,gl.RGBA,gl.UNSIGNED_BYTE,data);h=alloc(ctx,T.TEXTURE2D,{device:d.handle,gl:gl,texture:gt,width:w,height:hh,desc:desc,bytes:bytes});s.textureBytes+=bytes;return h;}
if(method==='CreateRenderTargetView'){d=deviceOf(ctx,args[0]);tex=obj(ctx,args[1],T.TEXTURE2D);gl=d.gl;if(tex.kind==='backbuffer')return alloc(ctx,T.RTV,{device:d.handle,resource:tex.handle,framebuffer:null,backbuffer:true});var fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex.texture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE){gl.deleteFramebuffer(fb);throw unsupported('Render-target framebuffer is incomplete.');}gl.bindFramebuffer(gl.FRAMEBUFFER,null);return alloc(ctx,T.RTV,{device:d.handle,resource:tex.handle,framebuffer:fb,backbuffer:false});}
if(method==='CreateDepthStencilView'){d=deviceOf(ctx,args[0]);return alloc(ctx,T.DSV,{device:d.handle,defaultDepth:true});}
if(method==='CreateShaderResourceView'){d=deviceOf(ctx,args[0]);tex=obj(ctx,args[1],T.TEXTURE2D);return alloc(ctx,T.SRV,{device:d.handle,resource:tex.handle});}
if(method==='CreateVertexShader'||method==='CreatePixelShader'){d=deviceOf(ctx,args[0]);var kind=method==='CreateVertexShader'?T.VS:T.PS,src=String(args[1]||'');if(src.length>256*1024)throw quota('Shader source is too large.');return alloc(ctx,kind,{device:d.handle,gl:d.gl,shader:compile(d.gl,kind,src),sourceLength:src.length});}
if(method==='CreateInputLayout'){d=deviceOf(ctx,args[0]);var els=Array.isArray(args[1])?args[1].slice(0,32):[];return alloc(ctx,T.LAYOUT,{device:d.handle,elements:els});}
if(method==='CreateSamplerState'){d=deviceOf(ctx,args[0]);desc=args[1]||{};gl=d.gl;var sm=gl.createSampler?gl.createSampler():null;if(sm){var min=String(desc.minFilter||'LINEAR').toUpperCase()==='NEAREST'?gl.NEAREST:gl.LINEAR,mag=String(desc.magFilter||'LINEAR').toUpperCase()==='NEAREST'?gl.NEAREST:gl.LINEAR;gl.samplerParameteri(sm,gl.TEXTURE_MIN_FILTER,min);gl.samplerParameteri(sm,gl.TEXTURE_MAG_FILTER,mag);gl.samplerParameteri(sm,gl.TEXTURE_WRAP_S,String(desc.addressU||'CLAMP').toUpperCase()==='WRAP'?gl.REPEAT:gl.CLAMP_TO_EDGE);gl.samplerParameteri(sm,gl.TEXTURE_WRAP_T,String(desc.addressV||'CLAMP').toUpperCase()==='WRAP'?gl.REPEAT:gl.CLAMP_TO_EDGE);}return alloc(ctx,T.SAMPLER,{device:d.handle,gl:gl,sampler:sm,desc:desc});}
if(method==='CreateRasterizerState'){d=deviceOf(ctx,args[0]);return alloc(ctx,T.RASTERIZER,{device:d.handle,desc:args[1]||{}});}
if(method==='CreateBlendState'){d=deviceOf(ctx,args[0]);return alloc(ctx,T.BLEND,{device:d.handle,desc:args[1]||{}});}
if(method==='CreateDepthStencilState'){d=deviceOf(ctx,args[0]);return alloc(ctx,T.DEPTHSTATE,{device:d.handle,desc:args[1]||{}});}
if(method==='Release'){o=obj(ctx,args[0]);deleteObject(ctx,o);return true;}
if(method==='IASetInputLayout'){c=contextOf(ctx,args[0]);c.state.layout=iv(args[1]);if(c.state.layout)obj(ctx,c.state.layout,T.LAYOUT);return true;}
if(method==='IASetVertexBuffers'){c=contextOf(ctx,args[0]);var start=iv(args[1]),bufs=Array.isArray(args[2])?args[2]:[args[2]],strides=Array.isArray(args[3])?args[3]:[args[3]],offs=Array.isArray(args[4])?args[4]:[args[4]];for(i=0;i<bufs.length;i++){obj(ctx,bufs[i],T.BUFFER);c.state.vertexBuffers[start+i]={buffer:iv(bufs[i]),stride:iv(strides[i]),offset:iv(offs[i])};}return true;}
if(method==='IASetIndexBuffer'){c=contextOf(ctx,args[0]);if(!args[1]){c.state.indexBuffer=null;return true;}obj(ctx,args[1],T.BUFFER);c.state.indexBuffer={buffer:iv(args[1]),format:String(args[2]||'R16_UINT'),offset:iv(args[3])};return true;}
if(method==='IASetPrimitiveTopology'){c=contextOf(ctx,args[0]);c.state.topology=iv(args[1],TOPO.TRIANGLELIST);return true;}
if(method==='VSSetShader'){c=contextOf(ctx,args[0]);if(args[1])obj(ctx,args[1],T.VS);c.state.vs=iv(args[1]);return true;}
if(method==='PSSetShader'){c=contextOf(ctx,args[0]);if(args[1])obj(ctx,args[1],T.PS);c.state.ps=iv(args[1]);return true;}
if(method==='PSSetShaderResources'){c=contextOf(ctx,args[0]);start=iv(args[1]);var views=Array.isArray(args[2])?args[2]:[args[2]];for(i=0;i<views.length;i++){if(views[i])obj(ctx,views[i],T.SRV);c.state.resources[start+i]=iv(views[i]);}return true;}
if(method==='PSSetSamplers'){c=contextOf(ctx,args[0]);start=iv(args[1]);var sams=Array.isArray(args[2])?args[2]:[args[2]];for(i=0;i<sams.length;i++){if(sams[i])obj(ctx,sams[i],T.SAMPLER);c.state.samplers[start+i]=iv(sams[i]);}return true;}
if(method==='OMSetRenderTargets'){c=contextOf(ctx,args[0]);var rtvs=Array.isArray(args[1])?args[1]:[args[1]];c.state.rtvs=[];for(i=0;i<rtvs.length;i++)if(rtvs[i]){obj(ctx,rtvs[i],T.RTV);c.state.rtvs.push(iv(rtvs[i]));}c.state.dsv=iv(args[2]);if(c.state.dsv)obj(ctx,c.state.dsv,T.DSV);return true;}
if(method==='RSSetViewports'){c=contextOf(ctx,args[0]);var vp=Array.isArray(args[1])?args[1][0]:args[1];c.state.viewport=vp||null;return true;}
if(method==='RSSetState'){c=contextOf(ctx,args[0]);c.state.rasterizer=iv(args[1]);if(c.state.rasterizer)obj(ctx,c.state.rasterizer,T.RASTERIZER);return true;}
if(method==='OMSetBlendState'){c=contextOf(ctx,args[0]);c.state.blend=iv(args[1]);if(c.state.blend)obj(ctx,c.state.blend,T.BLEND);return true;}
if(method==='OMSetDepthStencilState'){c=contextOf(ctx,args[0]);c.state.depthState=iv(args[1]);if(c.state.depthState)obj(ctx,c.state.depthState,T.DEPTHSTATE);return true;}
if(method==='SetShaderUniforms'||method==='SetShaderConstants'){c=contextOf(ctx,args[0]);var values=args[1]||{};for(var uk in values)if(Object.prototype.hasOwnProperty.call(values,uk))c.state.uniforms[uk]=values[uk];return true;}
if(method==='SetUniform'){c=contextOf(ctx,args[0]);c.state.uniforms[String(args[1]||'')]=args[2];return true;}
if(method==='ClearRenderTargetView'){c=contextOf(ctx,args[0]);rtv=obj(ctx,args[1],T.RTV);c.state.rtvs=[rtv.handle];bindTarget(ctx,c);gl=c.gl;var col=Array.isArray(args[2])?args[2]:[0,0,0,1];gl.clearColor(nv(col[0]),nv(col[1]),nv(col[2]),col.length>3?nv(col[3],1):1);gl.clear(gl.COLOR_BUFFER_BIT);return true;}
if(method==='ClearDepthStencilView'){c=contextOf(ctx,args[0]);gl=c.gl;bindTarget(ctx,c);gl.clearDepth(args[2]===undefined?1:nv(args[2],1));var mask=gl.DEPTH_BUFFER_BIT;if(args[3]!==undefined&&gl.STENCIL_BUFFER_BIT){gl.clearStencil(iv(args[3]));mask|=gl.STENCIL_BUFFER_BIT;}gl.clear(mask);return true;}
if(method==='Draw'){c=contextOf(ctx,args[0]);gl=c.gl;applyPipeline(ctx,c);gl.drawArrays(topology(gl,c.state.topology),iv(args[2]),iv(args[1]));return true;}
if(method==='DrawIndexed'){c=contextOf(ctx,args[0]);if(!c.state.indexBuffer)throw param('No index buffer is bound.');gl=c.gl;applyPipeline(ctx,c);var it=String(c.state.indexBuffer.format).toUpperCase()==='R32_UINT'?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,sz=it===gl.UNSIGNED_INT?4:2;gl.drawElements(topology(gl,c.state.topology),iv(args[1]),it,iv(c.state.indexBuffer.offset)+iv(args[2])*sz);return true;}
if(method==='UpdateSubresource'){o=obj(ctx,args[1]);data=typed(args[2],o.format||(o.desc&&o.desc.format));if(o.type===T.BUFFER){gl=o.gl;gl.bindBuffer(o.target,o.buffer);gl.bufferSubData(o.target,iv(args[3]),data);o.shadow=Array.prototype.slice.call(data);return true;}if(o.type===T.TEXTURE2D&&o.texture){gl=o.gl;gl.bindTexture(gl.TEXTURE_2D,o.texture);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,o.width,o.height,gl.RGBA,gl.UNSIGNED_BYTE,data);return true;}throw unsupported('UpdateSubresource supports buffers and Texture2D only.');}
if(method==='Map'){o=obj(ctx,args[1]);if(o.type!==T.BUFFER)throw unsupported('ExOS Map currently supports D3D11 buffers only.');if((o.bytes||0)>8*1024*1024)throw quota('Mapped buffer exceeds the 8 MiB XSH RPC map limit.');return{data:o.shadow?o.shadow.slice():[],byteWidth:o.bytes,format:o.format};}
if(method==='Unmap'){o=obj(ctx,args[1],T.BUFFER);data=typed(args[2],o.format);gl=o.gl;gl.bindBuffer(o.target,o.buffer);gl.bufferSubData(o.target,0,data);o.shadow=Array.prototype.slice.call(data);return true;}
if(method==='GenerateMips'){c=contextOf(ctx,args[0]);view=obj(ctx,args[1],T.SRV);tex=obj(ctx,view.resource,T.TEXTURE2D);gl=c.gl;gl.bindTexture(gl.TEXTURE_2D,tex.texture);gl.generateMipmap(gl.TEXTURE_2D);return true;}
if(method==='ResizeBuffers'){sc=obj(ctx,args[0],T.SWAPCHAIN);return resizeSurface(sc.surface,args[1],args[2]);}
if(method==='GetBackBuffer'){sc=obj(ctx,args[0],T.SWAPCHAIN);for(var q in s.objects)if(s.objects.hasOwnProperty(q)){o=s.objects[q];if(o.type===T.TEXTURE2D&&o.kind==='backbuffer'&&o.swapChain===sc.handle)return o.handle;}return 0;}
if(method==='Present'){sc=obj(ctx,args[0],T.SWAPCHAIN);try{sc.surface.gl.flush();}catch(ignoreFlush){}if(iv(args[1])>0&&typeof global.requestAnimationFrame==='function')return new Promise(function(resolve){global.requestAnimationFrame(function(){resolve(true);});});return true;}
if(method==='Flush'){c=contextOf(ctx,args[0]);try{c.gl.flush();}catch(ignore){}return true;}
throw unsupported('Unsupported d3d11.dll API: '+method);
}

global.jplopsoft_D3D11=API;
global.jplopsoft_d3d11Dispatch=dispatch;
global.jplopsoft_d3d11CleanupContext=cleanup;
})(window);
